spring.application.name=backend

# Use :8080 as a default if the variable isn't found
# Updated to match the environment variables added above
spring.datasource.url=jdbc:mysql://root:USvzxdJSlXixlnfHoxDKCtcfTJaYRKmr@turntable.proxy.rlwy.net:26184/railway
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
jwt.expiration=86400000

# This will output all configured properties to your console on startup
logging.level.org.springframework.boot.env.PropertySourcesLoader=DEBUG
logging.level.root=WARN
# We will see the real error now that Spring is configured correctly
logging.level.org.springframework.orm.jpa=DEBUG
cors.allowed-origins=${FRONTEND_URL}