spring.application.name=backend

# Use :8080 as a default if the variable isn't found
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:vendorbridge}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Taksh@@@3057}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
jwt.expiration=86400000

logging.level.root=WARN
# We will see the real error now that Spring is configured correctly
logging.level.org.springframework.orm.jpa=DEBUG